### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/bap-website#18]
src/app/not-found.tsx

There is no design for this but use this [code](https://github.com/acm-ucr/rishi-website/blob/dev/src/app/not-found.js) and [screenshot](https://snipboard.io/GxXM7s.jpg) as a reference. match the colors of this website

**Comment by prajeshElEvEn** [comment]
Oh I like this issue and would love to contribute.

**Comment by prajeshElEvEn** [comment]
> Oh I like this issue and would love to contribute.

I did. https://github.com/acm-ucr/bap-website/pull/31#issue-2555924326

**Comment by amarajaRW** [comment]
Match the colours of the website in figma design or the link to screenshot?
