### ISSUE TITLE
Implement Resources Page

### ISSUE THREAD

**Issue by JohnZ9865** [acm-ucr/bap-website#21]
src/app/resources/[section]/page.tsx

Resources page utilizes dynamic routing. We need to implement it such that going to website/resources/[resource_name_here], it'll arrive at this page here "src/app/resources/[section]/page.tsx", where depending on the route name a different result will be displayed every time.

For example, website/resources/resume will display this below:
<img width="324" alt="image" src="https://github.com/user-attachments/assets/491be960-71a9-42b0-ab81-29f348e6f285">

**Comment by Abumostafa12** [comment]
this has been assigned to Jonathan and Mostafa and its already done --- John Zhou
