### ISSUE TITLE
Professionals part 2

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/bap-website#25]
src/components/home/Professionals.tsx

1. find the icons in the public folder
2. using Next \<Image\> (not  \<img\>) add the icons under the PROFESSIONALS box already implemented in Professionals.tsx. 

<img width="607" alt="image" src="https://github.com/user-attachments/assets/96a8a6a3-5951-4593-a079-b3863dcdefd9">

**Comment by Abumostafa12** [comment]
picture of project
![Uploading Screenshot 2024-10-21 at 9.37.34 PM.png…]()
