### ISSUE TITLE
add social links

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/bap-website#85]
These icons should be clickable and should redirect to the appropriate socials

<img width="114" alt="image" src="https://github.com/user-attachments/assets/aa928fd5-4b40-46b8-8cb2-6a5e51e5df64">

**Comment by JohnZ9865** [comment]
https://www.instagram.com/ucrbap/?hl=en

**Comment by JohnZ9865** [comment]
https://www.linkedin.com/company/ucr-beta-alpha-psi/
